### PR TITLE
Embedding Images and Video

### PR DESCRIPTION
**Pull request by mohamedSabry0**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Awesome Job team
your files are well organized👌, the readme is very descriptive👌 and you have made good use of semantic👌 Html
Here are a few changes we have to make to get our project approved🙂
* [ ] let us add the hamburger beside the youtube logo as in the original page
* [ ] let us add append the search button to the input field in the navbar
currently, the page only displays the input field with the icon(icon ought to be button)
* [ ] let us add the avatar(image) of the user who uploaded the video
* [ ] let us add the number of views to the aside image thumbnail as in the original page
* [ ] let us fix the warnings returned by HTML [validator](https://validator.w3.org/nu/#file)

## That is it guys, do these changes and submit the project for review🙂


feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
Happy coding🙂

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi team :wave: 

You guys have done well fixing the issues pointed out earlier. However, there is very bad practise that you need to take care of. 

- [ ] It’s better to delete commented code. If you need to review a previous version of your code, use git history.

https://github.com/RodolfoRodriguezMata/First-microverse-project/blob/daa13df69083ccd3035de7f2125b8fb61d48fb9b/style.css#L172

https://github.com/RodolfoRodriguezMata/First-microverse-project/blob/daa13df69083ccd3035de7f2125b8fb61d48fb9b/style.css#L120

**Get rid of those commented codes and submit another code review request**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by ebukaume** [comment]
## Approved! :champagne: 

**Congratulations! :fireworks:  You guys can go ahead and merge this branch.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Pull request merged**
